### ISSUE TITLE
Suspected Off-By-One Error In Lerping Logic Causing An Invalid Read

### ISSUE THREAD

**Issue by Pastifier** [Pastifier/miniRT#1]
Check the log files in your repository. If Github doesn't allow you to pull the large `outfile.log` file for whatever reason. Use
```bash
$> ./miniRT > outfile.log 2> error.log
```
and compare. You'll find that there's a `y=-1` in there towards the end, usually. Just like we suspected! The rest is up to you <3

**Comment by MOMO24185** [comment]
Fixed it in the latest commit, there were multiple issues after that off by 1 value, also I think the get_pixel_color is broken, anyways the interpolation works but it has lots of artifacts within the final render so we might need to fine tune it cuz I think the issue is related to the combination of cdiff returns, the threshold, and possibly the lerp function.
